venv:
    source ./.venv/bin/activate

server port: venv
    uv run flask --app ./servers/src/servers/main.py run --port {{port}}

lb port: venv
    uv run flask --app ./lb/src/lb/app/app.py run --port {{port}}
